create database db2;
use db2;
create table Authors(author_id int auto_increment primary key, name varchar(20) not null, country varchar(20) not null);
insert into Authors values(1,'Sugatha Kumari', 'India');
select * from Authors;
insert into Authors values(2,'M T Vasudevan Nair','India');
insert into Authors values(3, 'Words worth', 'America');
insert into Authors values(4, 'O N V', 'India');
insert into Authors values(5, 'Shakespear', 'France'); 
select name from Authors;
select country from Authors;
select * from Authors where country='America';
alter table Authors rename column author_id to user_id;
alter table Authors drop state;
alter table Authors add state varchar(30) null;
select * from Authors order by user_id asc limit 2;
select * from Authors order by rand() limit 2;
select country as 'user_country' from Authors;